import random

word_list = [
    ("Hola", "Hello"),
    ("Adiós", "Goodbye"),
    ("Gracias", "Thank you"),
    ("Por favor", "Please"),
    ("Sí", "Yes"),
    ("No", "No"),
    ("Buenos días", "Good morning"),
    ("Buenas tardes", "Good afternoon"),
    ("Buenas noches", "Good night"),
    ("¿Cómo estás?", "How are you?"),
    ("Lo siento", "I'm sorry"),
    ("Salud", "Bless you"),
    ("¿Qué tal?", "What's up?"),
    ("¿Cómo te llamas?", "What's your name?"),
    ("Me llamo...", "My name is..."),
    ("Mucho gusto", "Nice to meet you"),
    ("Hasta luego", "See you later"),
    ("Hasta mañana", "See you tomorrow"),
    ("Por supuesto", "Of course"),
    ("No entiendo", "I don't understand"),
    ("¿Dónde está...?", "Where is...?"),
    ("Baño", "Bathroom"),
    ("Comida", "Food"),
    ("Agua", "Water"),
    ("Casa", "House"),
    ("Familia", "Family"),
    ("Amigo", "Friend"),
    ("Escuela", "School"),
    ("Trabajo", "Work"),
    ("Dinero", "Money"),
    ("Tiempo", "Time"),
    ("Hombre", "Man"),
    ("Mujer", "Woman"),
    ("Niño", "Boy"),
    ("Niña", "Girl"),
    ("Perro", "Dog"),
    ("Gato", "Cat"),
    ("Carro", "Car"),
    ("Bus", "Bus"),
    ("Tren", "Train"),
    ("Aeropuerto", "Airport"),
    ("Hotel", "Hotel"),
    ("Restaurante", "Restaurant"),
    ("Hospital", "Hospital"),
    ("Tienda", "Store"),
    ("Parque", "Park"),
    ("Playa", "Beach"),
    ("Montaña", "Mountain"),
    ("Ciudad", "City"),
    ("País", "Country"),
    ("Mundo", "World"),
    ("Día", "Day"),
    ("Noche", "Night"),
    ("Tarde", "Afternoon"),
    ("Mañana", "Morning/Tomorrow"),
    ("Ayer", "Yesterday"),
    ("Hoy", "Today"),
    ("Semana", "Week"),
    ("Mes", "Month"),
    ("Año", "Year"),
    ("Lunes", "Monday"),
    ("Martes", "Tuesday"),
    ("Miércoles", "Wednesday"),
    ("Jueves", "Thursday"),
    ("Viernes", "Friday"),
    ("Sábado", "Saturday"),
    ("Domingo", "Sunday"),
    ("Enero", "January"),
    ("Febrero", "February"),
    ("Marzo", "March"),
    ("Abril", "April"),
    ("Mayo", "May"),
    ("Junio", "June"),
    ("Julio", "July"),
    ("Agosto", "August"),
    ("Septiembre", "September"),
    ("Octubre", "October"),
    ("Noviembre", "November"),
    ("Diciembre", "December"),
    ("Uno", "One"),
    ("Dos", "Two"),
    ("Tres", "Three"),
    ("Cuatro", "Four"),
    ("Cinco", "Five"),
    ("Seis", "Six"),
    ("Siete", "Seven"),
    ("Ocho", "Eight"),
    ("Nueve", "Nine"),
    ("Diez", "Ten"),
    ("Ropa", "Clothes"),
    ("Zapatos", "Shoes"),
    ("Coche", "Car"),
    ("Puerta", "Door"),
    ("Ventana", "Window"),
    ("Libro", "Book"),
    ("Mesa", "Table"),
    ("Silla", "Chair"),
    ("Cama", "Bed"),
    ("Cuadro", "Picture"),
    ("Pared", "Wall"),
    ("Techo", "Ceiling"),
    ("Piso", "Floor"),
    ("Luz", "Light"),
    ("Teléfono", "Telephone"),
    ("Computadora", "Computer"),
    ("Ratón", "Mouse"),
    ("Teclado", "Keyboard"),
    ("Pantalla", "Screen"),
    ("Internet", "Internet"),
    ("Correo", "Mail"),
    ("Carta", "Letter"),
    ("Periódico", "Newspaper"),
    ("Revista", "Magazine"),
    ("Televisión", "Television"),
    ("Radio", "Radio"),
    ("Música", "Music"),
    ("Película", "Movie"),
    ("Juego", "Game"),
    ("Deporte", "Sport"),
    ("Fútbol", "Soccer"),
    ("Baloncesto", "Basketball"),
    ("Tenis", "Tennis"),
    ("Natación", "Swimming"),
    ("Correr", "Running"),
    ("Bicicleta", "Bicycle"),
    ("Moto", "Motorcycle"),
    ("Avión", "Airplane"),
    ("Barco", "Boat"),
    ("Tren", "Train"),
    ("Autobús", "Bus"),
    ("Camión", "Truck"),
    ("Taxi", "Taxi"),
    ("Metro", "Subway"),
    ("Bicicleta", "Bicycle"),
    ("A pie", "On foot"),
    ("Conducir", "To drive"),
    ("Caminar", "To walk"),
    ("Correr", "To run"),
    ("Saltar", "To jump"),
    ("Nadar", "To swim"),
    ("Leer", "To read"),
    ("Escribir", "To write"),
    ("Hablar", "To speak"),
    ("Escuchar", "To listen"),
    ("Ver", "To see"),
    ("Mirar", "To look"),
    ("Comer", "To eat"),
    ("Beber", "To drink"),
    ("Cocinar", "To cook"),
    ("Lavar", "To wash"),
    ("Limpiar", "To clean"),
    ("Comprar", "To buy"),
    ("Vender", "To sell"),
    ("Abrir", "To open"),
    ("Cerrar", "To close"),
    ("Encender", "To turn on"),
    ("Apagar", "To turn off"),
    ("Subir", "To go up"),
    ("Bajar", "To go down"),
    ("Entrar", "To enter"),
    ("Salir", "To exit"),
    ("Llegar", "To arrive"),
    ("Ir", "To go"),
    ("Venir", "To come"),
    ("Querer", "To want"),
    ("Necesitar", "To need"),
    ("Gustar", "To like"),
    ("Amar", "To love"),
    ("Odiar", "To hate"),
    ("Esperar", "To wait"),
    ("Buscar", "To look for"),
    ("Encontrar", "To find"),
    ("Perder", "To lose"),
    ("Ganar", "To win"),
    ("Jugar", "To play"),
    ("Trabajar", "To work"),
    ("Estudiar", "To study"),
    ("Aprender", "To learn"),
    ("Enseñar", "To teach"),
    ("Preguntar", "To ask"),
    ("Responder", "To answer"),
    ("Decir", "To say"),
    ("Contar", "To count"),
    ("Pagar", "To pay"),
    ("Hacer", "To do"),
    ("Crear", "To create"),
    ("Construir", "To build"),
    ("Romper", "To break"),
    ("Reparar", "To repair"),
    ("Planchar", "To iron"),
    ("Doblar", "To fold"),
    ("Coser", "To sew"),
    ("Cortar", "To cut"),
    ("Pegar", "To glue"),
    ("Unir", "To join"),
    ("Separar", "To separate"),
    ("Mezclar", "To mix"),
    ("Agitar", "To shake"),
    ("Batir", "To beat"),
    ("Freír", "To fry"),
    ("Hornear", "To bake"),
    ("Asar", "To roast"),
    ("Hervir", "To boil"),
    ("Guisar", "To stew"),
    ("Sofreír", "To sauté"),
    ("Saltear", "To stir-fry"),
    ("Marinar", "To marinate"),
    ("Cocinar", "To cook"),
    ("Servir", "To serve"),
    ("Probar", "To taste"),
    ("Masticar", "To chew"),
    ("Tragar", "To swallow"),
    ("Saborear", "To savor"),
    ("Oler", "To smell"),
    ("Tocar", "To touch"),
    ("Sentir", "To feel"),
    ("Pensar", "To think"),
    ("Recordar", "To remember"),
    ("Olvidar", "To forget"),
    ("Conocer", "To know a person"),
    ("Saber", "To know information"),
    ("Entender", "To understand"),
    ("Comprender", "To understand"),
    ("Enseñar", "To teach"),
    ("Aprender", "To learn"),
    ("Estudiar", "To study"),
    ("Leer", "To read"),
    ("Escribir", "To write"),
    ("Hablar", "To speak"),
    ("Escuchar", "To listen"),
]


score = 0
attempts = 1

while(True):
    num_words = len(word_list)
    rand = random.randint(0, num_words-1)
    word_es = word_list[rand][0].lower()
    word_en = word_list[rand][1].lower()
    user_ans = input(f'what is the english word for: {word_es}? ').lower()
    if user_ans == word_en:
        score += 1
        print(f'You\'re right! Your score is {score} out of {attempts} \n')
        word_list.pop(rand)
    else:
        print(f'The correct answer is {word_en}')
        print(f'Try again. Your score is {score} out of {attempts} \n')
    attempts += 1